name: minaret
description: Minaret is a cross platform e-Solat application

version: 4.0.4+19

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # sdk
  flutter:
    sdk: flutter
  # components (first party: flutter.dev, dart.dev)
  http: ^0.12.0
  intl: ^0.16.1
  html: ^0.14.0
  url_launcher: ^5.4.2
  package_info: ^0.4.0
  path_provider: ^1.6.5
  shared_preferences: ^0.5.6+3
  # components (third party)
  sqflite: ^1.3.0
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  font_awesome_flutter: ^8.7.0
  flutter_launcher_icons: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Varela
      fonts:
        - asset: font/varela.ttf

# run 'flutter pub run flutter_launcher_icons:main' to update
flutter_icons:
  ios: true
  android: true
  image_path_ios: "img/icon/icon.png"
  image_path_android: "img/icon/icon.png"
  adaptive_icon_foreground: "img/icon/adaptive_fg.png"
  adaptive_icon_background: "img/icon/adaptive_bg.png"

