name: waktuku
description: Malaysia Muslim Prayer Time App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  intl: ^0.16.1
  sqflite: ^1.2.0
  path_provider: ^1.5.1
  html: ^0.14.0+3
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Varela
      fonts:
        - asset: font/varela.ttf
